### ISSUE TITLE
Add install order

### ISSUE THREAD

**Issue by tylerauerbeck** [rht-labs/enablement-framework#10]
Occasionally the helm install will fail because the `CheCluster` is applied before the CRD is available. Need to update the chart to be smart enough to apply in the appropriate order.

**Comment by jtudelag** [comment]
Hey @tylerauerbeck , I got hit by his 100% of the times I have tried to install the chart ...
Not sure why, never got it right. Also it is quite hard to debug this because the dry-run does not work due to the "lookup" function...

I haven't found a way to specify the order in which manifest are rendered/process...
I will propose to separate this in two charts, install any operator first, and then the rest of the content as suggested here: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource 

Thoughts?

**Comment by tylerauerbeck** [comment]
@jtudelag I think that's the route to go for right now (and then just have two seperate `helm install` commands). There are a few other ideas I'm working on right now, but will need some time to prove them out.

**Comment by tylerauerbeck** [comment]
@jtudelag Actually I came up with a way to use post-install hooks to get this working. I'll PR this here shortly and then we should be good to go.

**Comment by tylerauerbeck** [comment]
Handled in #19
